# .github/workflows/gitlab-sync.yml
name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "saniyaacharya288@gmail.com"
          git remote add gitlab git@gitlab.com:saniyaacharya04/3-tier-app-Deployment.git
          git push gitlab main
