name: CI Pipeline with GitLab Sync

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_TAG: ${{ github.sha }}
  AWS_REGION: us-east-1

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install
          npm run build

      - name: Run backend tests with Docker Compose
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "backend"
          test-command: "npm test -- --coverage"

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/

      - name: Publish Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: backend/coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
          thresholds: '50 75'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t ${{ secrets.ECR_FRONTEND_URI }}:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.ECR_FRONTEND_URI }}:${{ env.IMAGE_TAG }}

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t ${{ secrets.ECR_BACKEND_URI }}:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.ECR_BACKEND_URI }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-app-url
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init & Apply
        run: |
          cd terra-config
          terraform init
          terraform apply -auto-approve

      - name: Redeploy on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/backend
            git pull origin main
            npm install
            pm2 restart backend || npm start

  mirror-to-gitlab:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "Saniya Acharya"
          git config --global user.email "saniyaacharya288"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITHUBSYNCTOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/saniyaacharya04/3-tier-app-Deployment.git
          git push gitlab main --force --verbose
